### ISSUE TITLE
why the "how" section is broken

### ISSUE THREAD

**Issue by lun-4** [lun-4/obsidian2web#26]
"# how" isn't being recognized as a section by koino, maybe????

see it in prod here https://l4.pm/wiki/Personal%20Wiki/Articles/resolution%20changes%20considered%20harmful.html

**Comment by regalialong** [comment]
![image](https://github.com/lun-4/obsidian2web/assets/126194895/9f670301-6a68-4e88-ab79-f6717cd3c7d0)
I believe this can be closed?

**Comment by lun-4** [comment]
#27 sorta supersedes it, the issue still happens, just that i hotfixed it by not doing triple-tick codeblock

**Comment by lun-4** [comment]
#27 is closed, this is fixed, life is happy
